"""creating messege models

Revision ID: 1688acefb1f1
Revises: 074fa8350636
Create Date: 2024-01-11 05:58:28.655171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1688acefb1f1'
down_revision = '074fa8350636'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
